const SubmitAIForm = () => {
  const [formData, setFormData] = useState({
    name: '',
    websiteUrl: '',
    generationType: 'self'
  });

  const handleChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  return (
    <div>
      <h2 className="text-2xl font-semibold text-center">Tools you need to submit</h2>
      <div className="max-w-3xl mx-auto mt-8 space-y-6">
        <div className="space-y-4">
          <FormField
            label="Name"
            placeholder="Copy AI"
            required
            value={formData.name}
            onChange={(e) => handleChange('name', e.target.value)}
          />
          <FormField
            label="Website URL"
            placeholder='Please enter the tool url, such as: "https://www.copy.ai"'
            type="url"
            required
            value={formData.websiteUrl}
            onChange={(e) => handleChange('websiteUrl', e.target.value)}
          />
          
          <div>
            <label className="block mb-2">
              <span className="text-gray-700">
                <span className="text-red-500">*</span> Choose how to generate tool information
              </span>
            </label>
            <div className="space-y-3">
              <GenerationOption
                title="Generated by Toolify"
                description="All content and translations are generated by Toolify AI"
                isSelected={formData.generationType === 'toolify'}
                onClick={() => handleChange('generationType', 'toolify')}
              />
              <GenerationOption
                title="Do it myself"
                description="Provide tool information myself in English only, translated by Toolify AI"
                isPrimary
                isNew
                isSelected={formData.generationType === 'self'}
                onClick={() => handleChange('generationType', 'self')}
              />
            </div>
          </div>

          <div className="mt-8 flex justify-between items-center border-t pt-6">
            <div>
              <div className="text-2xl font-bold">Total: $ 99</div>
              <div className="text-gray-600 text-sm">No queue, listed within 48 hours</div>
            </div>
            <button className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors">
              Pay $ 99
            </button>
          </div>
        </div>
      </div>
      <ExampleSection />
    </div>
  );
};

const ExampleSection = () => (
  <div className="max-w-5xl mx-auto mt-16 bg-gray-50 p-8 rounded-2xl">
    <div className="grid md:grid-cols-2 gap-8">
      <div className="relative">
        <div className="bg-purple-100 p-4 rounded-xl">
          <img 
            src="/api/placeholder/400/400" 
            alt="Freelancing Platform Example" 
            className="rounded-lg w-full"
          />
        </div>
      </div>
      
      <div className="space-y-6">
        <h2 className="text-2xl font-bold">Submit a Tool Example</h2>
        
        <div>
          <h3 className="font-medium mb-4">You will get:</h3>
          <div className="space-y-6">
            <BenefitItem
              title="Appeared in Listing and Just Launched within 48 hours, no queue."
            />
            <BenefitItem
              title="Border Highlight"
              description="Users can quickly spot you in the list and increase the number of clicks."
            />
            <BenefitItem
              title="Get dofollow links and boost your SEO"
              description="Your website will get no less than 6 quality dofollow links from Toolify. This is a key factor in improving your search engine optimization rankings."
            />
            <BenefitItem
              title="Listing & Traffic Forever"
              description="Your tool stays permanently on toolify's list and gets a constant stream of clicks and subscribers."
            />
            <BenefitItem
              title="Get toolify AI Launch embeds"
              description="Get toolify's AI certification and link toolify AI certification to your website."
            />
          </div>
        </div>
      </div>
    </div>
  </div>
);

const ToolifyDashboard = () => {
  const [activeAction, setActiveAction] = useState('submit-ai');

  const handleCardClick = (action) => {
    setActiveAction(action);
  };

  const actionCards = [
    {
      title: "Submit AI",
      description: "Submit your AI tools, get traffic",
      action: "submit-ai"
    },
    {
      title: "Advertise AI* 🔥",
      description: "Pay-per-click, featured promotions, automated ad placement",
      action: "advertise"
    },
    {
      title: "Guest Posts / Link Insert",
      description: "Guest posts/link insert on Toolify",
      action: "guest-posts"
    },
    {
      title: "Update AI",
      description: "Update your tool's information.",
      action: "update-ai"
    },
    {
      title: "Submit GPT",
      description: "Submit your gpt for more people to use.",
      action: "submit-gpt"
    },
    {
      title: "More Business",
      description: "Such as: link exchanges, Twitter posts, videos, etc.",
      action: "more-business"
    }
  ];

  const renderActiveForm = () => {
    switch (activeAction) {
      case 'advertise':
        return <AdvertiseForm />;
      case 'submit-ai':
        return <SubmitAIForm />;
      case 'guest-posts':
        return <GuestPostForm />;
      case 'update-ai':
        return <UpdateAIForm />;
      default:
        return <div className="text-center text-gray-600 py-8">Form coming soon...</div>;
    }
  };

  return (
    <div className="flex-1 overflow-y-auto">
      {/* Fixed Header */}
      <div className="flex-none bg-white border-b px-6 py-4 mt-7">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <h1 className="text-3xl font-bold">Your AIs on Toolify</h1>
          <button className="px-4 py-2 border rounded-lg hover:bg-gray-50">
            My Orders →
          </button>
        </div>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-7xl mx-auto p-6 space-y-8">
          <p className="text-gray-700">
            Toolify AI can help you reach millions of AI users and your potential customers worldwide. 
            Reach AI enthusiasts, AI entrepreneurs, AI investors, VPs and more to increase your product visibility, 
            trial rates and paying users.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-8">
            <StatsCard icon={FileText} value="8M+" label="PAGE VIEWS" />
            <StatsCard icon={Users} value="5.1M+" label="MONTHLY VISITS" />
            <StatsCard icon={MessageCircle} value="350K+" label="SUBSCRIBERS" />
            <StatsCard icon={Users} value="55%" label="DESKTOP USERS" />
            <StatsCard icon={MessageCircle} value="03:23" label="AVG TIME ON SITE" />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 text-sm">
            <FeatureItem>Top AI Tools Directory</FeatureItem>
            <FeatureItem>Dofollow backlink</FeatureItem>
            <FeatureItem>Multi-language intro</FeatureItem>
            <FeatureItem>Listing & Traffic forever</FeatureItem>
            <FeatureItem>Value for Founders&Startups</FeatureItem>
          </div>

          <div>
            <h2 className="text-xl font-semibold mb-4">Choose what you want</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4">
              {actionCards.map((card) => (
                <ActionCard
                  key={card.action}
                  title={card.title}
                  description={card.description}
                  isPrimary={card.action === activeAction}
                  onClick={() => handleCardClick(card.action)}
                />
              ))}
            </div>
          </div>

          {renderActiveForm()}
        </div>
      </div>
    </div>
  );
};

export default ToolifyDashboard;